Repository rancher/elemental-cli, pull requests merged in 2022-05, with the labels that each got.

#192 Add docs for commands and generator
  .github/workflows/docs.yaml
  Makefile
  README.md
  docs/elemental.md
  docs/elemental_build-disk.md
  docs/elemental_build-iso.md
  docs/elemental_cloud-init.md
  docs/elemental_convert-disk.md
  docs/elemental_install.md
  docs/elemental_new.md
  docs/elemental_pull-image.md
  docs/elemental_reset.md
  docs/elemental_run-stage.md
  docs/elemental_upgrade.md
  docs/elemental_version.md
  docs/generate_docs.go
  go.sum
Labels: documentation

#195 Add job to auto create PR for updated docs
  .github/workflows/update-cmd-docs.yaml
Labels: documentation, enhancement

#211 Fix efi image size calculation
  pkg/action/build-iso.go
Labels: bug
